---
- name: host
  hosts: all
  tasks:
    - name: Template a file to /root/myhosts
      ansible.builtin.template:
        src: hosts.j2
        dest: /root/myhosts
      when: inventory_hostname in groups.dev
