---
- name: issue
  hosts: all
  tasks:
    - name: Copy using inline content
      ansible.builtin.copy:
        content: 'Development'
        dest: /etc/issue
      when: inventory_hostname in groups.dev

    - name: Copy using inline content
      ansible.builtin.copy:
        content: 'Test'
        dest: /etc/issue
      when: inventory_hostname in groups.test

    - name: Copy using inline content
      ansible.builtin.copy:
        content: 'Production'
        dest: /etc/issue
      when: inventory_hostname in groups.proxy


